#ifndef I2SAPPCONFIG_H
#define I2SAPPCONFIG_H

#include "driver/gpio.h"

#define I2S_WORD_SELECT GPIO_NUM_10
#define I2S_SERIAL_CLOCK GPIO_NUM_9

#define I2S_MIC_SERIAL_DATA GPIO_NUM_11     // SD
#define I2S_SPEAKER_SERIAL_DATA GPIO_NUM_12 // SDIN

#define I2S_BUFFER_SIZE 480
#define I2S_CHUNK_SIZE 240 * 6

#define I2S_TX_SAMPLE_SIZE (I2S_DATA_BIT_WIDTH_16BIT * I2S_BUFFER_SIZE)
#define I2S_RX_SAMPLE_SIZE (I2S_DATA_BIT_WIDTH_16BIT * I2S_BUFFER_SIZE)

#endif